"""ERA5 variable and level mappings.

Constants for ERA5 variables, pressure levels, model levels, and MARS parameter codes.
"""

# 2D single-level variables (no vertical levels needed)
# All available single-level ERA5 variables
ALL_SINGLE_LEVEL_VARIABLES = {
    "10m_u_component_of_wind",
    "10m_v_component_of_wind",
    "100m_u_component_of_wind",
    "100m_v_component_of_wind",
    "2m_dewpoint_temperature",
    "2m_temperature",
    "boundary_layer_height",
    "convective_available_potential_energy",
    "convective_precipitation",
    "eastward_turbulent_surface_stress",
    "evaporation",
    "friction_velocity",
    "geopotential_at_surface",
    "high_vegetation_cover",
    "instantaneous_10m_wind_direction",
    "instantaneous_10m_wind_speed",
    "instantaneous_eastward_turbulent_surface_stress",
    "instantaneous_northward_turbulent_surface_stress",
    "land_sea_mask",
    "large_scale_precipitation",
    "leaf_area_index_high_vegetation",
    "leaf_area_index_low_vegetation",
    "low_vegetation_cover",
    "mean_sea_level_pressure",
    "mean_surface_downward_long_wave_radiation_flux",
    "mean_surface_downward_short_wave_radiation_flux",
    "mean_surface_latent_heat_flux",
    "mean_surface_sensible_heat_flux",
    "mean_top_downward_long_wave_radiation_flux",
    "mean_top_downward_short_wave_radiation_flux",
    "mean_top_net_long_wave_radiation_flux",
    "mean_top_net_short_wave_radiation_flux",
    "northward_turbulent_surface_stress",
    "potential_evaporation",
    "runoff",
    "sea_ice_cover",
    "sea_surface_temperature",
    "skin_reservoir_content",
    "skin_temperature",
    "snow_cover",
    "snow_depth",
    "snowfall",
    "soil_temperature_level_1",
    "soil_temperature_level_2",
    "soil_temperature_level_3",
    "soil_temperature_level_4",
    "soil_type",
    "surface_latent_heat_flux",
    "surface_net_solar_radiation",
    "surface_net_thermal_radiation",
    "surface_pressure",
    "surface_sensible_heat_flux",
    "surface_solar_radiation_downwards",
    "surface_thermal_radiation_downwards",
    "top_net_solar_radiation",
    "top_net_thermal_radiation",
    "total_cloud_cover",
    "total_column_cloud_liquid_water",
    "total_column_cloud_ice_water",
    "total_column_ozone",
    "total_column_rain_water",
    "total_column_supercooled_liquid_water",
    "total_column_water",
    "total_column_water_vapour",
    "total_precipitation",
    "type_of_high_vegetation",
    "type_of_low_vegetation",
    "uv_visible_albedo_for_direct_radiation",
    "uv_visible_albedo_for_diffuse_radiation",
    "vertical_integral_of_divergence_of_moisture_flux",
    "vertical_integral_of_eastward_water_vapour_flux",
    "vertical_integral_of_northward_water_vapour_flux",
    "volumetric_soil_water_layer_1",
    "volumetric_soil_water_layer_2",
    "volumetric_soil_water_layer_3",
    "volumetric_soil_water_layer_4",
}

# All available 3D pressure-level ERA5 variables
ALL_PRESSURE_LEVEL_VARIABLES = {
    "divergence",
    "fraction_of_cloud_cover",
    "geopotential",
    "ozone_mass_mixing_ratio",
    "potential_vorticity",
    "quality_indicators_cloud_icing_level",
    "quality_indicators_cloud_type",
    "relative_humidity",
    "specific_cloud_ice_water_content",
    "specific_cloud_liquid_water_content",
    "specific_humidity",
    "temperature",
    "u_component_of_wind",
    "v_component_of_wind",
    "vorticity",
}

# All available 3D model-level ERA5 variables
ALL_MODEL_LEVEL_VARIABLES = {
    "divergence",
    "fraction_of_cloud_cover",
    "geopotential",
    "ozone_mass_mixing_ratio",
    "potential_vorticity",
    "quality_indicators_cloud_icing_level",
    "quality_indicators_cloud_type",
    "relative_humidity",
    "specific_cloud_ice_water_content",
    "specific_cloud_liquid_water_content",
    "specific_humidity",
    "temperature",
    "u_component_of_wind",
    "v_component_of_wind",
    "vorticity",
}

# Default: 13 variables (8 single-level surface + 5 pressure-level atmospheric)
DEFAULT_VARIABLES = [
    # 2D surface variables
    "10m_u_component_of_wind",
    "10m_v_component_of_wind",
    "100m_u_component_of_wind",
    "100m_v_component_of_wind",
    "2m_temperature",
    "surface_solar_radiation_downwards",
    "surface_pressure",
    "total_precipitation",
    # 3D variables at pressure levels
    "temperature",
    "u_component_of_wind",
    "v_component_of_wind",
    "relative_humidity",
    "geopotential",
]

# All available pressure levels in ERA5
ALL_PRESSURE_LEVELS = [
    "1",
    "2",
    "3",
    "5",
    "7",
    "10",
    "20",
    "30",
    "50",
    "70",
    "100",
    "125",
    "150",
    "175",
    "200",
    "225",
    "250",
    "300",
    "350",
    "400",
    "450",
    "500",
    "550",
    "600",
    "650",
    "700",
    "750",
    "775",
    "800",
    "825",
    "850",
    "875",
    "900",
    "925",
    "950",
    "975",
    "1000",
]

# Default: 1000, 975, 950 hPa (lowest 3 pressure levels, ~110m, ~300m, ~560m altitude)
DEFAULT_PRESSURE_LEVELS = ["1000", "975", "950"]

# All available model levels in ERA5 (1-137, where 137 is the surface)
ALL_MODEL_LEVELS = [str(i) for i in range(1, 138)]

# Default: 133, 134, 135, 136, 137 (lowest 5 model levels, ~150m, ~100-120m, ~50-70m, ~10-15m, surface)
DEFAULT_MODEL_LEVELS = ["133", "134", "135", "136", "137"]

# Mapping of variable names to MARS parameter short codes
VARIABLE_TO_MARS_PARAM = {
    # Single-level variables
    "10m_u_component_of_wind": "10u",
    "10m_v_component_of_wind": "10v",
    "100m_u_component_of_wind": "100u",
    "100m_v_component_of_wind": "100v",
    "2m_temperature": "2t",
    "2m_dewpoint_temperature": "2d",
    "surface_solar_radiation_downwards": "ssrd",
    "surface_pressure": "sp",
    "total_precipitation": "tp",
    "mean_sea_level_pressure": "msl",
    "boundary_layer_height": "blh",
    "convective_precipitation": "cp",
    "evaporation": "e",
    "snowfall": "sf",
    "snow_depth": "sd",
    "sea_ice_cover": "ci",
    "sea_surface_temperature": "sst",
    "skin_temperature": "skt",
    "skin_reservoir_content": "src",
    "soil_type": "slt",
    "surface_latent_heat_flux": "slhf",
    "surface_sensible_heat_flux": "sshf",
    "surface_thermal_radiation_downwards": "strd",
    "surface_net_solar_radiation": "ssr",
    "surface_net_thermal_radiation": "str",
    "top_net_solar_radiation": "tsr",
    "top_net_thermal_radiation": "ttr",
    "total_cloud_cover": "tcc",
    # 3D variables (pressure/model levels)
    "temperature": "t",
    "u_component_of_wind": "u",
    "v_component_of_wind": "v",
    "geopotential": "z",
    "relative_humidity": "r",
    "specific_humidity": "q",
    "vertical_velocity": "w",
    "divergence": "d",
    "vorticity": "vo",
    "potential_vorticity": "pv",
    "fraction_of_cloud_cover": "cc",
    "specific_cloud_ice_water_content": "ciwc",
    "specific_cloud_liquid_water_content": "clwc",
    "ozone_mass_mixing_ratio": "o3",
}
